# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-07 10:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('label', models.CharField(max_length=200)),
                ('sub_label', models.CharField(max_length=200)),
                ('score_pos', models.DecimalField(decimal_places=10, max_digits=20)),
                ('score_neg', models.DecimalField(decimal_places=10, max_digits=20)),
                ('score_neu', models.DecimalField(decimal_places=10, max_digits=20)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
